repository:
  default_branch: master
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: false
  braanches:
    - name: master
      protection:
        restrictions:
          users: [nosknut]
    - name: feature/devensiv
      protection:
        required_pull_request_reviews:
          required_approving_review_count: 1
        enforce_admins: true
        restrictions:
          users: [nosknut, devensiv]
